module.exports = {
  ROOT_PATH : "./",
  EXTERNALS: {
    "storybook-addon-specifications": "storybook-addon-specifications",
    "@storybook/addon-actions": "@storybook/addon-actions",
    "@storybook/addon-info": "@storybook/addon-info",
    "@storybook/addon-links": "@storybook/addon-links",
    "@storybook/react": "@storybook/react",
    "browser-sync": "browser-sync",
    "browser-sync-webpack-plugin": "browser-sync-webpack-plugin",
    "pkgfiles": "pkgfiles",
    "react": "react", /* exclude react */
    "react-addons-test-utils": "react-addons-test-utils",
    "react-helmet": "react-helmet",
    "react-test-renderer": "react-test-renderer",
    "autoprefixer": "autoprefixer",
    "babel-cli": "babel-cli",
    "babel-core": "babel-core",
    "babel-loader": "babel-loader",
    "babel-preset-es2015": "babel-preset-es2015",
    "babel-preset-react": "babel-preset-react",
    "clean-webpack-plugin": "clean-webpack-plugin",
    "copy-webpack-plugin": "copy-webpack-plugin",
    "css-loader": "css-loader",
    "dotenv-webpack": "dotenv-webpack",
    "enzyme": "enzyme",
    "expect": "expect",
    "extract-text-webpack-plugin": "extract-text-webpack-plugin",
    "file-loader": "file-loader",
    "humps": "humps",
    "postcss-loader": "postcss-loader",
    "style-loader": "style-loader",
    "webpack": "webpack",
    "static-site-generator-webpack-plugin": "static-site-generator-webpack-plugin",
    "webpack-dev-server": "webpack-dev-server",
    "lodash": "lodash",
    "storybook-addon-specifications": "storybook-addon-specifications",
    "react-router": "react-router",
    "react-router-dom": "react-router-dom",
    "jquery": "jquery",
    "jQuery": "jQuery",
  }
}
